name: Notify

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  notify:
    name: Send Telegram notifications
    runs-on: ubuntu-latest

    steps:
      - name: Run Upptime Monitor
        id: incident
        uses: upptime/uptime-monitor@v1.40.1

      # Debug: stampa i valori di output
      - name: Print incident flags
        run: |
          echo "Has Open Incident: ${{ steps.incident.outputs.hasOpenIncident }}"
          echo "Has Closed Incident: ${{ steps.incident.outputs.hasClosedIncident }}"

      # Notifica incidente (DOWN)
      - name: Notify Telegram on incident
        if: steps.incident.outputs.hasOpenIncident == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="⚠️ *Attenzione!* Uno o più servizi sono *offline*. Controlla il repository Upptime." \
            -d parse_mode=Markdown

      # Notifica ripristino (UP)
      - name: Notify Telegram on recovery
        if: steps.incident.outputs.hasClosedIncident == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ *Servizi online!* I servizi monitorati risultano ora *operativi*." \
            -d parse_mode=Markdown
