name: Notify

on:
  schedule:
    - cron: "*/5 * * * *"  # ogni 5 minuti
  workflow_dispatch:        # consente di avviarlo manualmente

jobs:
  notify:
    name: Send Telegram notifications
    runs-on: ubuntu-latest

    steps:
      - name: Check for incidents
        id: incident
        uses: upptime/uptime-monitor@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Notifica DOWN
      - name: Notify Telegram on incident
        if: steps.incident.outputs.hasOpenIncident == 'true'
        run: |
          curl -s -X POST https://api.tel
