name: Notify

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  notify:
    name: Send Telegram notifications
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Run Upptime Monitor
        id: incident
        uses: upptime/uptime-monitor@v1.40.1

      - name: Print incident flags (debug)
        run: |
          echo "Open Incident: ${{ steps.incident.outputs.hasOpenIncident }}"
          echo "Closed Incident: ${{ steps.incident.outputs.hasClosedIncident }}"

      - name: Notify Telegram on incident
        if: steps.incident.outputs.hasOpenIncident == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="⚠️ *Attenzione!* Uno o più servizi risultano *offline*." \
            -d parse_mode=Markdown

      - name: Notify Telegram on recovery
        if: steps.incident.outputs.hasClosedIncident == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="✅ *Servizio ripristinato!* Tutti i servizi risultano nuovamente *online*." \
            -d parse_mode=Markdown
